[package]
name = "gobrapls"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.16", features = ["derive"] }
log = "0.4.22"
log4rs = "1.3.0"
sha2 = "0.10.8"
tempfile = "3.12.0"
tokio = { version = "1.40.0", features = ["full"] }
tower-lsp = "0.20.0"
